# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bar.Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='table_no',
            field=models.PositiveIntegerField(),
        ),
    ]
